# Makefile.dep created Tue May 28 00:49:45 PDT 2019
protocol.o: protocol.cpp protocol.h sockets.h
sockets.o: sockets.cpp sockets.h
cix.o: cix.cpp protocol.h sockets.h logstream.h
cixd.o: cixd.cpp protocol.h sockets.h logstream.h
